---
- name: Purge iptables-persistent
  apt:
    state: absent
    purge: true
    name:
      - iptables-persistent
      - netfilter-persistent

- name: Delete iptables-persistent configuration
  file:
    state: absent
    path: '{{ iptables__conf_dir }}'
